name: pyrosetta
channels:
  - https://pose:foldtree@conda.graylab.jhu.edu
  - schrodinger
  - defaults
dependencies:
  - pip
  - python=3.6
  - ipython
  - pytest=3.8.*
  - pytest-cov
  - flake8
  - pyrosetta
  - pymol
  - pip:
    - jupyter
    - black==18.6b4
    - flake8-bugbear
